### ISSUE TITLE
Add four more fields

### ISSUE THREAD

**Issue by uclaros** [lutraconsulting/qgis-nnpa-reporting#4]
The following four columns should be added to the report tree widget:
| Column name | default field name |
| --- | --- |
| Grid Reference | "grid refer" |
| Latin Name | "latin name" |
| Sample Recorder | "recorder" |
| Survey Name | "survey nam" |

Changes needed:
- [x] Add `QgsSettings` entries for the field names
- [x] Add widgets in the `SettingsDialog`
- [x] Add columns to the result `QTreeWidget`
- [x] Update logic to get comma separated unique values for those fields in the results
- [x] Make sure the fields are also added when exporting results as a vector layer

**Comment by ldebek** [comment]
PR: https://github.com/lutraconsulting/qgis-nnpa-reporting/pull/5
